import { grade6Subjects, grade6Topics, getTopic, getSubject, projectTemplates } from "../data/grade6-plan.js";
import { topicStatuses, sortAssignments, localDateKey } from "./grade6-state.js";
import { lessons } from "./grade6-practice.js";

export const escape = value => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const button = (label, action, attrs = "", style = "secondary") => `<button type="button" class="g6-button g6-button--${style}" data-g6-action="${action}" ${attrs}>${label}</button>`;
const topicButton = (topic, label = "Open topic", style = "secondary") => button(escape(label), "topic", `data-id="${topic.id}"`, style);
const heading = (eyebrow, title, copy = "") => `<header class="g6-page-heading"><p class="eyebrow">${eyebrow}</p><h1 tabindex="-1" id="g6-heading">${title}</h1>${copy ? `<p>${copy}</p>` : ""}</header>`;
const field = (label, value, attrs = "", rows = 4) => `<label class="g6-field"><span>${escape(label)}</span><textarea rows="${rows}" maxlength="20000" ${attrs}>${escape(value)}</textarea><span class="g6-print-text">${escape(value) || "No notes yet."}</span></label>`;
const noteStatus = (data, id) => data.topics[id]?.status || "new";
const status = (data, id) => `<span class="g6-status g6-status--${noteStatus(data, id)}">${topicStatuses[noteStatus(data, id)]}</span>`;
const dateLabel = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString("en-CA", { month: "short", day: "numeric", year: "numeric" }) : "No due date";
function factorTree() {
    return `<svg class="g6-factor-tree" viewBox="0 0 340 210" role="img" aria-label="Factor tree: 36 splits into 4 and 9. Four splits into 2 and 2. Nine splits into 3 and 3."><g fill="none" stroke="currentColor" stroke-width="2" opacity=".22"><path d="M170 42L90 100M170 42L250 100M90 100L50 165M90 100L130 165M250 100L210 165M250 100L290 165"/></g><g fill="var(--g6-paper)"><circle cx="170" cy="36" r="27"/><circle cx="90" cy="99" r="23"/><circle cx="250" cy="99" r="23"/></g><g fill="var(--g6-blue)"><circle cx="50" cy="166" r="23"/><circle cx="130" cy="166" r="23"/><circle cx="210" cy="166" r="23"/><circle cx="290" cy="166" r="23"/></g><g text-anchor="middle" font-size="21" font-family="inherit" font-weight="650" fill="currentColor"><text x="170" y="43">36</text><text x="90" y="106">4</text><text x="250" y="106">9</text></g><g text-anchor="middle" font-size="20" font-family="inherit" fill="#fcfcfe"><text x="50" y="173">2</text><text x="130" y="173">2</text><text x="210" y="173">3</text><text x="290" y="173">3</text></g></svg>`;
}
function subjectRows(data) {
    return `<div class="g6-subject-list">${grade6Subjects.map(subject => {
        const started = subject.topics.filter(t => noteStatus(data, t.id) !== "new").length;
        return `<button type="button" class="g6-subject-row g6-color-${subject.color}" data-g6-action="subject" data-id="${subject.id}"><span class="g6-subject-number">${subject.mark}</span><span class="g6-subject-copy"><strong>${subject.title}</strong><span>${subject.description}</span><small>${subject.topics.length} topics · ${started} started</small></span><span class="g6-arrow" aria-hidden="true">↗</span></button>`;
    }).join("")}</div>`;
}
function assignmentRow(item) {
    const overdue = item.due && item.due < localDateKey() && !item.done;
    return `<article class="g6-task ${item.done ? "is-done" : ""}"><label class="g6-check"><input type="checkbox" data-g6-task="${escape(item.id)}" ${item.done ? "checked" : ""}><span class="sr-only">Mark ${escape(item.title)} complete</span></label><div><span class="g6-task-meta">${getSubject(item.subjectId).short} · ${item.source === "teacher" ? "Teacher assignment" : "Extra practice"}</span><h3>${escape(item.title)}</h3><p class="${overdue ? "g6-overdue" : ""}">${overdue ? "Past due · " : ""}${dateLabel(item.due)}</p>${item.notes ? `<p class="g6-task-notes">${escape(item.notes)}</p>` : ""}</div>${button("Edit", "edit-task", `data-id="${escape(item.id)}"`, "text")}</article>`;
}
function weekly(data, ui) {
    const tasks = sortAssignments(data.assignments);
    const open = tasks.filter(t => !t.done), complete = tasks.filter(t => t.done);
    const pinned = data.pinned.map(getTopic).filter(Boolean);
    const active = data.activePractice;
    return `${heading("Math Gen · Grade 6", "A little progress.<br>Every day.", "Your schoolwork, practice, and new ideas. All in one place.")}
        <section class="g6-week-layout">
            <div class="g6-work-panel"><div class="g6-section-title"><div><p class="eyebrow">This week</p><h2>Your next steps</h2></div>${button("+ Add a task", "add-task")}</div>
                ${open.length ? open.map(assignmentRow).join("") : `<div class="g6-empty"><span class="g6-empty-line" aria-hidden="true"></span><h3>A fresh page for Grade 6.</h3><p>Add homework when the teacher sends it. The year plan is ready to explore.</p>${button("Add your first task", "add-task", "", "primary")}</div>`}
                ${complete.length ? `<details class="g6-completed" ${ui.showCompleted ? "open" : ""}><summary>Completed tasks (${complete.length})</summary>${complete.map(assignmentRow).join("")}</details>` : ""}
                <p class="g6-footnote">The teacher's outline is a year plan. Weekly assignments and dates are added separately.</p>
            </div>
            <aside class="g6-spotlight"><p class="eyebrow">${active && !active.completedAt ? "Ready to continue" : "A place to start · Extra practice"}</p><h2>${active && !active.completedAt ? escape(getTopic(active.topicId).title) : "Big numbers.<br>Small building blocks."}</h2>${active && !active.completedAt ? `<p>Your answers and hints are saved with this practice round.</p>${button("Continue practice →", "resume-practice", "", "primary")}` : `${factorTree()}<p>Every composite number can be built from primes. See how 36 comes apart.</p>${topicButton(getTopic("factors"), "Explore prime factors →", "primary")}`}</aside>
        </section>
        ${pinned.length ? `<section><div class="g6-section-title"><div><p class="eyebrow">Chosen by you</p><h2>My focus topics</h2></div></div><div class="g6-focus-list">${pinned.map(t => `<div><span class="eyebrow">${getSubject(t.subjectId).short}</span><h3>${escape(t.title)}</h3>${status(data, t.id)}${topicButton(t, "Continue →", "text")}</div>`).join("")}</div></section>` : ""}
        <section><div class="g6-section-title"><div><p class="eyebrow">The teacher's full plan</p><h2>A year of discovery.</h2></div>${button("See the year plan →", "nav", 'data-page="subjects"', "text")}</div>${subjectRows(data)}</section>
        <div class="g6-year-note"><strong>Across the year</strong><span>Classroom Economy all year · EQAO math practice in late spring · Science Fair and final projects near year-end</span></div>`;
}
function subjects(data, ui) {
    const subject = getSubject(ui.subjectId);
    if (!subject) return `${heading("Grade 6 · Year plan", "Room to grow.", "All six subjects from the teacher's outline. Choose a subject to see its topics.")}${subjectRows(data)}<p class="g6-footnote">Topic order is for browsing. It is not the teacher's lesson schedule.</p>`;
    return `${button("← All subjects", "nav", 'data-page="subjects"', "text")}${heading(`Grade 6 · ${subject.topics.length} topics`, subject.title, subject.description)}<div class="g6-topic-list">${subject.topics.map((t, i) => `<article><span class="g6-topic-number">${String(i + 1).padStart(2, "0")}</span><div><h2>${escape(t.title)}</h2><p>${escape(t.scope)}</p>${status(data, t.id)}</div>${topicButton(t, "Explore →", "text")}</article>`).join("")}</div><p class="g6-footnote">From the teacher's year plan. Activities inside each topic are extra practice.</p>`;
}
function topicPage(data, ui) {
    const t = getTopic(ui.topicId), subject = getSubject(t.subjectId), note = data.topics[t.id];
    const lesson = lessons[t.practice];
    return `${button(`← ${subject.title}`, "subject", `data-id="${subject.id}"`, "text")}${heading(`${subject.title} · Grade 6`, escape(t.title), escape(t.scope))}
        <div class="g6-topic-tools no-print">${button(data.pinned.includes(t.id) ? "✓ In my focus topics" : "+ Add to my focus topics", "pin", `data-id="${t.id}"`)}${button("Print topic", "print", "", "text")}</div>
        ${lesson ? `<section class="g6-lesson"><div><p class="eyebrow">Learn</p><h2>Start with the idea.</h2><p>${escape(lesson.rule)}</p><h3>A worked example</h3><p class="g6-example">${escape(lesson.example)}</p></div>${t.id === "factors" ? factorTree() : ""}</section>` : `<div class="g6-source-note"><strong>Start with your class materials.</strong><p>Use the teacher's text, examples, and instructions for this topic. The prompts below are extra practice.</p></div>`}
        ${t.subjectId === "health" ? `<p class="g6-footnote">Use general or fictional examples. Keep private questions and personal health details offline.</p>` : ""}
        <section class="g6-notebook"><div class="g6-section-title"><div><p class="eyebrow">Try · Extra practice</p><h2>${escape(t.activity)}</h2></div>${t.practice ? button("Start math practice →", "start-practice", `data-id="${t.id}"`, "primary") : ""}</div><p class="g6-footnote">These notes save on this browser. Written work needs a review with the class criteria.</p>${t.prompts.map((p, i) => field(`${i + 1}. ${p}`, note?.responses[i] || "", `data-g6-note="${t.id}" data-index="${i}" id="note-${i}"`)).join("")}</section>
        <section class="g6-reflection"><div><p class="eyebrow">Reflect</p><h2>How does this feel?</h2><p>This is your own check. It is separate from a teacher's assessment.</p></div><label class="g6-field"><span>My understanding</span><select data-g6-status="${t.id}">${Object.entries(topicStatuses).map(([id, label]) => `<option value="${id}" ${noteStatus(data, t.id) === id ? "selected" : ""}>${label}</option>`).join("")}</select></label></section>
        ${projectTemplates.filter(p => p.id === t.id || (t.id === "novel" && p.id === "novel-project") || (t.id === "persuasive" && p.id === "persuasive-essay")).map(p => `<div class="g6-year-note"><span>Take this work further in the project planner.</span>${button(`Open ${escape(p.title)} →`, "project", `data-id="${p.id}"`, "text")}</div>`).join("")}`;
}
function practiceHome(data, ui = {}) {
    return `${heading("Grade 6 · Extra practice", "Try. Check. Try again.", "Choose a math topic. Read an example, use a hint, and explain your method.")}${data.activePractice ? `<div class="g6-resume"><div><strong>${escape(getTopic(data.activePractice.topicId).title)}</strong><p>${data.activePractice.completedAt ? "Your last round is ready to review." : "Your current round is saved."}</p></div>${button(data.activePractice.completedAt ? "Review round →" : "Continue round →", "resume-practice", "", "primary")}</div>` : ""}
        <label class="g6-field g6-level"><span>Number range for new rounds</span><select id="g6-level"><option value="core">Core practice</option><option value="stretch" ${ui.level === "stretch" ? "selected" : ""}>Larger numbers</option></select></label><div class="g6-practice-list">${grade6Topics.filter(t => t.practice).map(t => `<article><div><h2>${escape(t.title)}</h2><p>${t.practice === "review" ? "Mixed practice · Original questions" : "Six questions · Hints included"}</p></div>${button("Practise →", "start-practice", `data-id="${t.id}"`, "text")}</article>`).join("")}</div><p class="g6-footnote">For reading, writing, science, and other subjects, open a topic in Subjects. The Grade 5 archive still includes spelling practice and speech.</p>`;
}
function practiceRound(data, ui) {
    const round = ui.recordId ? data.history.find(r => r.id === ui.recordId) : data.activePractice;
    if (!round) return practiceHome(data);
    const t = getTopic(round.topicId), readOnly = Boolean(round.completedAt), checked = Object.keys(round.results).length > 0;
    const correct = round.questions.filter(q => round.results[q.id]?.correct).length;
    return `${button("← Math practice", "nav", 'data-page="practice"', "text")}${heading(`Extra practice · ${round.level === "stretch" ? "Larger numbers" : "Core practice"}`, escape(t.title), "Work at your own pace. Use the hint if you need a next step.")}
        <div class="g6-round-tools no-print">${topicButton(t, "Read the example", "text")}${button("Print round", "print", "", "text")}</div>
        ${readOnly ? `<div class="g6-result" role="status"><strong>Round complete. All six answers checked.</strong><p>${round.questions.filter(q => round.attempts[q.id] === 1 && !round.hints[q.id]).length} answered on the first check without a hint. You can review your answers below.</p></div>` : checked ? `<div class="g6-result" role="status"><strong>${correct} of 6 answers checked.</strong><p>Look at the hints for the remaining questions. Then try again.</p></div>` : ""}
        <form data-g6-form="practice" class="g6-questions">${round.questions.map((q, i) => {
            const result = round.results[q.id], solved = result?.correct === true;
            return `<section class="g6-question ${solved ? "is-correct" : ""}"><span class="g6-question-number">${String(i + 1).padStart(2, "0")}</span><div><label for="answer-${q.id}">${escape(q.prompt)}</label><div class="g6-answer-row"><input id="answer-${q.id}" data-g6-answer="${q.id}" name="${q.id}" type="text" autocomplete="off" spellcheck="false" maxlength="100" value="${escape(round.answers[q.id] || "")}" ${solved || readOnly ? "readonly" : ""} ${result && !solved ? 'aria-invalid="true"' : ""} aria-describedby="help-${q.id}"><span>${escape(q.unit)}</span>${solved ? '<span class="g6-correct-label">✓ Correct</span>' : ""}</div><div id="help-${q.id}">${result && !solved ? `<p class="g6-answer-feedback">${String(round.answers[q.id] || "").trim() ? "Not yet. Use the hint and check your method." : "Enter an answer when you are ready."}</p>` : ""}${solved ? `<p class="g6-answer-explanation">${escape(q.explanation)}</p>` : ""}</div>${!solved && !readOnly ? `${button(round.hints[q.id] ? "Hint is open" : "Show a hint", "hint", `data-id="${q.id}"`, "text")}${round.hints[q.id] ? `<p class="g6-hint">${escape(q.hint)}</p>` : ""}` : ""}</div></section>`;
        }).join("")}${!readOnly ? `<div class="g6-form-actions no-print"><button type="submit" class="g6-button g6-button--primary">Check my answers</button><span>Fractions such as 1/2 are accepted. Do not type units.</span></div>` : ""}</form>
        ${readOnly ? `<div class="g6-form-actions no-print">${button("New round", "start-practice", `data-id="${t.id}"`, "primary")}${topicButton(t, "Reflect on this topic", "text")}</div>` : ""}`;
}
function projects(data, ui) {
    const template = projectTemplates.find(p => p.id === ui.projectId);
    if (!template) return `${heading("Grade 6 · Projects", "Good work takes steps.", "Plan, draft, review, and finish. Keep the teacher's criteria beside your work.")}<div class="g6-project-list">${projectTemplates.map(p => { const completed = data.projects[p.id]?.done.filter(Boolean).length || 0; return `<article><span class="eyebrow">${getSubject(p.subjectId).short} · ${p.timing}</span><h2>${p.title}</h2><p>${completed} of ${p.steps.length} steps marked complete</p><progress max="${p.steps.length}" value="${completed}" aria-label="${p.title}: completed steps"></progress>${button("Open planner →", "project", `data-id="${p.id}"`, "text")}</article>`; }).join("")}</div>`;
    const note = data.projects[template.id];
    return `${button("← All projects", "nav", 'data-page="projects"', "text")}${heading(`${getSubject(template.subjectId).title} · ${template.timing}`, template.title, "Add the teacher's instructions to your notes. Mark a step complete when your work is ready.")}<div class="g6-round-tools no-print">${button("Print planner", "print")}</div><div class="g6-project-steps">${template.steps.map((step, i) => `<section><div class="g6-step-heading"><span class="g6-step-number">${i + 1}</span><h2>${step}</h2><label class="g6-check"><input type="checkbox" data-g6-project-done="${template.id}" data-index="${i}" ${note?.done[i] ? "checked" : ""}><span>Step complete</span></label></div>${field(`Notes for ${step.toLowerCase()}`, note?.notes[i] || "", `data-g6-project-note="${template.id}" data-index="${i}"`, 5)}</section>`).join("")}</div><p class="g6-footnote">These planners are based on the year outline. Exact instructions and due dates come from the teacher.</p>`;
}
function progress(data) {
    const started = grade6Topics.filter(t => noteStatus(data, t.id) !== "new").length;
    const reviewed = grade6Topics.filter(t => noteStatus(data, t.id) === "independent").length;
    return `${heading("Grade 6 · Progress", "See how far you've come.", "Completed work and your own understanding are shown separately.")}
        <div class="g6-progress-summary"><p><strong>${started}</strong> topics started</p><p><strong>${data.history.length}</strong> practice rounds completed</p><p><strong>${reviewed}</strong> topics you can explain</p></div>
        <section><div class="g6-section-title"><h2>My topic check</h2><span class="g6-footnote">Your own reflection · Not a teacher grade</span></div>${grade6Subjects.map(subject => `<details class="g6-progress-subject"><summary><strong>${subject.title}</strong><span>${subject.topics.filter(t => noteStatus(data, t.id) !== "new").length} / ${subject.topics.length} started</span></summary>${subject.topics.map(t => `<div class="g6-progress-topic">${topicButton(t, t.title, "text")}${status(data, t.id)}</div>`).join("")}</details>`).join("")}</section>
        <section><div class="g6-section-title"><h2>Practice history</h2></div>${data.history.length ? `<div class="g6-history">${data.history.map(round => `<article><div><h3>${escape(getTopic(round.topicId).title)}</h3><p>${escape(new Date(round.completedAt).toLocaleDateString("en-CA"))} · ${round.questions.filter(q => round.attempts[q.id] === 1 && !round.hints[q.id]).length}/6 first check, without hints</p></div>${button("Review answers →", "record", `data-id="${escape(round.id)}"`, "text")}</article>`).join("")}</div>` : `<p class="g6-empty-copy">Finish a practice round to see your saved answers here.</p>`}</section>
        <div class="g6-year-note"><span>Work is saved in this browser. Download a copy to keep with your school files.</span>${button("Download my work", "export", "", "text")}</div>`;
}
function taskForm(data, ui) {
    const task = data.assignments.find(t => t.id === ui.taskId);
    return `${button("← This week", "nav", 'data-page="week"', "text")}${heading("Grade 6 · This week", task ? "Edit your task." : "One clear next step.", "Copy the assignment from the teacher, or add your own extra practice.")}
        <form data-g6-form="task" class="g6-task-form"><label class="g6-field"><span>Task title</span><input name="title" required maxlength="160" value="${escape(task?.title)}" placeholder="For example: Read chapter 3 and write a summary"></label><div class="g6-form-grid"><label class="g6-field"><span>Subject</span><select name="subjectId">${grade6Subjects.map(s => `<option value="${s.id}" ${s.id === task?.subjectId ? "selected" : ""}>${s.title}</option>`).join("")}</select></label><label class="g6-field"><span>Source</span><select name="source"><option value="teacher" ${task?.source !== "practice" ? "selected" : ""}>Teacher assignment</option><option value="practice" ${task?.source === "practice" ? "selected" : ""}>Extra practice</option></select></label></div><label class="g6-field"><span>Due date (optional)</span><input name="due" type="date" value="${escape(task?.due)}"></label><label class="g6-field"><span>Instructions or materials (optional)</span><textarea name="notes" rows="5" maxlength="3000">${escape(task?.notes)}</textarea></label><div class="g6-form-actions"><button type="submit" class="g6-button g6-button--primary">${task ? "Save changes" : "Add task"}</button>${button("Cancel", "nav", 'data-page="week"', "text")}</div></form>`;
}
export function renderGrade6(data, ui) {
    const nav = [["week", "This Week"], ["subjects", "Subjects"], ["practice", "Practice"], ["projects", "Projects"], ["progress", "Progress"]];
    const current = ui.page === "topic" ? "subjects" : ui.page === "round" ? "practice" : ui.page === "task" ? "week" : ui.page;
    const content = ui.page === "subjects" ? subjects(data, ui) : ui.page === "topic" ? topicPage(data, ui) : ui.page === "practice" ? practiceHome(data, ui) : ui.page === "round" ? practiceRound(data, ui) : ui.page === "projects" ? projects(data, ui) : ui.page === "progress" ? progress(data) : ui.page === "task" ? taskForm(data, ui) : weekly(data, ui);
    return `<div class="g6-shell"><header class="g6-header no-print"><button type="button" class="g6-brand" data-g6-action="nav" data-page="week"><img src="./assets/favicon.svg" alt="" width="34" height="34"><span>Math Gen<small>Growing into Grade 6</small></span></button><span class="g6-grade-tag">GRADE 6</span>${button("Grade 5 archive ↗", "archive", "", "text")}</header><nav class="g6-nav no-print" aria-label="Grade 6 sections">${nav.map(([id, label]) => `<button type="button" data-g6-action="nav" data-page="${id}" ${current === id ? 'aria-current="page"' : ""}>${label}</button>`).join("")}</nav>
        <p id="g6-save-status" class="g6-save-status ${ui.saveError ? "is-error" : ""}" role="status">${escape(ui.saveError || "Work saves in this browser")}</p>
        ${ui.notice ? `<p class="g6-notice" role="status">${escape(ui.notice)}</p>` : ""}
        ${ui.pendingPractice ? `<section class="g6-replace-prompt" role="region" aria-label="Current practice"><h2>You have an unfinished round.</h2><p>Continue it, or replace it with new practice. Replacing it removes the unfinished answers.</p>${button("Continue saved round", "resume-practice", "", "primary")}${button("Replace unfinished round", "replace-practice")}</section>` : ""}
        <div class="g6-content">${content}</div><footer class="g6-footer"><span>Math Gen · One step at a time.</span><span>Grade 6 · Teacher plan + extra practice</span></footer></div>`;
}
